name: "Submit to Web Store"
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: oven-sh/setup-bun@v2

      - name: Install packages
        run: bun install

      - name: Build the extension
        run: |
          bun run build
        # bun run build:firefox

      - name: Package the extension into a zip artifact
        run: |
          bun run package
        # bun run package:firefox

      - name: Browser Platform Publish
        uses: PlasmoHQ/bpp@v3
        with:
          keys: ${{ secrets.SUBMIT_KEYS }}
          artifact: build/chrome-mv3-prod.zip
          # chrome-file: build/chrome-mv3-prod.zip
          # firefox-file: build/firefox-mv3-prod.zip
