name: Testing

on:
  pull_request:
  push:
    branches:
      - master
      - dev

jobs:
  testing:
    name: Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - name: Install packages
        run: bun install

      - name: Run linting
        run: bun run lint
